MODEL:
  TYPE: vssm
  NAME: defm_base_e300
  DROP_PATH_RATE: 0.4
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 3, 16, 2]
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    CONVFFN: False
    ADD_SE: False

